# -*- coding: utf-8 -*-
"""etl-clientes-parcial02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0XwfhZOcRz9opkmBJEMa5L2Lylt9wSQ
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline-2532032022/refs/heads/main/data/raw/F_clientes.csv"

clientes = pd.read_csv(url)
clientes.head()

#EXPLORACION DE DATOS

#clientes.shape #filas, columnas
#clientes.columns
#clientes.info()
clientes.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(clientes):
    clientes.columns = (
        clientes.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return clientes

# Limpia solamente textos
def limpiar_texto(clientes):
    for col in clientes.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        clientes[col] = clientes[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        clientes[col] = clientes[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return clientes

#APLICA LIMPIEZA GENERAL
clientes = normalizar_columnas(clientes)
clientes = limpiar_texto(clientes)
clientes=clientes.drop_duplicates() #Elimina duplicados

#LIMPIEZA DE DATOS ESPECIFICOS

#Cliente
import unicodedata

clientes["cliente"] = (
    clientes["cliente"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)
clientes["cliente"] = clientes["cliente"].replace(["", " ", "NULL", "null", "None", "nan"],pd.NA)

#Correo
clientes["correo"] = clientes["correo"].astype("string").str.lower().str.strip()
clientes["correo"] = clientes["correo"].replace(
    ["", " ", "NULL", "null", "None", "nan"], pd.NA
)

#Telefono
clientes["telefono"] = clientes["telefono"].replace(["", " ", "NULL", "null", "None", "nan"],pd.NA)

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

clientes_validos=clientes[
    clientes['cliente'].notna()&
    clientes['correo'].notna()&
    clientes['telefono'].notna()
].copy()


clientes_rechazados=clientes[
    clientes["cliente"].isna() |
    clientes['correo'].isna() |
    clientes['telefono'].isna()
].copy()

#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['cliente']):
    motivos.append("cliente_vacio")

  if pd.isna(row['correo']):
    motivos.append("correo_vacio")

  if pd.isna(row['telefono']):
    motivos.append("telefono_vacio")

  return ";".join(motivos)

clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo,axis=1)

#VERIFICAR SI HAY DATOS NULOS
print(clientes.isna().sum())

#EXPORTAR ARCHIVOS

clientes_validos.to_csv("clientes_curated.csv", index=False)

clientes_rechazados.to_csv("clientes_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

if clientes_validos.empty:
    print("⚠ No hay datos válidos")

if clientes_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    clientes_validos.to_sql('clientes_curated_parcial02', engine, if_exists='append', index=False)
    clientes_rechazados.to_sql('clientes_rejects_parcial02', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM clientes_curated_parcial02 LIMIT 10",
    engine
)

#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM clientes_rejects_parcial02 LIMIT 10",
    engine
)