# -*- coding: utf-8 -*-
"""etl-envios-parcial02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Qp2-tzKMYshn66wvJz-TiVFJANyYkys
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline-2532032022/refs/heads/main/data/raw/F_envios.csv"

envios = pd.read_csv(url)
envios.head()

#EXPLORACION DE DATOS

#envios.shape #filas, columnas
#envios.columns
#envios.info()
envios.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(envios):
    envios.columns = (
        envios.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return envios

# Limpia solamente textos
def limpiar_texto(envios):
    for col in envios.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        envios[col] = envios[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        envios[col] = envios[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return envios

#APLICA LIMPIEZA GENERAL
envios = normalizar_columnas(envios)
envios = limpiar_texto(envios)
envios= envios.drop_duplicates() #Elimina duplicados

# Ver correos duplicados y cuántas veces se repiten
envios["estado_envio"].value_counts()[envios["estado_envio"].value_counts() > 1]

#LIMPIEZA DE DATOS ESPECIFICOS

#id_pedido
envios["id_pedido"] = envios["id_pedido"].astype("string").str.lower().str.strip()
envios["id_pedido"] = envios["id_pedido"].replace(["", " ", "NULL", "null", "None", "nan"], pd.NA)

#direccion
envios["direccion"] = (envios["direccion"].astype(str).str.strip().str.title())

#fecha_envio
envios["fecha_envio"] = pd.to_datetime(
    envios["fecha_envio"],
    errors="coerce",
    format="mixed"
)

#estado_envio
envios["estado_envio"] = (
    envios["estado_envio"].astype(str).str.strip().str.lower().map({
        "entregado":"Entregado",
        "devuelto":"Devuelto",
        "en ruta":"En Ruta",
        "preparando":"Preparando"
        })
)

envios

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

envios_validos=envios[
    envios['id_pedido'].notna()&
    envios['direccion'].notna()&
    envios['fecha_envio'].notna()&
    envios['estado_envio'].notna()
].copy()


envios_rechazados=envios[
    envios['id_pedido'].isna()|
    envios['direccion'].isna()|
    envios['fecha_envio'].isna()|
    envios['estado_envio'].isna()
].copy()

#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['id_pedido']):
    motivos.append("id_pedido_vacio")

  if pd.isna(row['direccion']):
    motivos.append("direccion_vacio")

  if pd.isna(row['fecha_envio']):
    motivos.append("fecha_envio_vacio")

  if pd.isna(row['estado_envio']):
    motivos.append("estado_envio_vacio")

  return ";".join(motivos)

envios_rechazados["motivo_rechazo"] = envios_rechazados.apply(motivo,axis=1)

#VERIFICAR SI HAY DATOS NULOS
print(envios.isna().sum())

#EXPORTAR ARCHIVOS

envios_validos.to_csv("envios_curated.csv", index=False)

envios_rechazados.to_csv("envios_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

if envios_validos.empty:
    print("⚠ No hay datos válidos")

if envios_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    envios_validos.to_sql('envios_curated_parcial02', engine, if_exists='append', index=False)
    envios_rechazados.to_sql('envios_rejects_parcial02', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM envios_curated_parcial02 LIMIT 10",
    engine
)

#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM envios_rejects_parcial02 LIMIT 10",
    engine
)