# -*- coding: utf-8 -*-
"""etl-pedidos-parcial02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wc3GAQ7u1JeIptqU-6gryVrm-sTpg6YY
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd
import numpy as np
import re

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline-2532032022/refs/heads/main/data/raw/F_pedidos.csv"

pedidos = pd.read_csv(url)
pedidos.head()

#EXPLORACION DE DATOS

#pedidos.shape #filas, columnas
#pedidos.columns
#pedidos.info()
pedidos.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(pedidos):
    pedidos.columns = (
        pedidos.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return pedidos

# Limpia solamente textos
def limpiar_texto(pedidos):
    for col in pedidos.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        pedidos[col] = pedidos[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        pedidos[col] = pedidos[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return pedidos

#APLICA LIMPIEZA GENERAL
pedidos = normalizar_columnas(pedidos)
pedidos = limpiar_texto(pedidos)
pedidos= pedidos.drop_duplicates() #Elimina duplicados

# Ver estados duplicados y cuántas veces se repiten
pedidos["estado"].value_counts()[pedidos["estado"].value_counts() > 1]

#LIMPIEZA DE DATOS ESPECIFICOS

#id_pedido
pedidos["id_cliente"] = pedidos["id_cliente"].astype("string").str.lower().str.strip()
pedidos["id_cliente"] = pedidos["id_cliente"].replace(["", " ", "NULL", "null", "None", "nan"], pd.NA)

#fecha_pedido
pedidos["fecha_pedido"] = pd.to_datetime(
    pedidos["fecha_pedido"],
    errors="coerce",
    format="mixed"
)

#monto
def limpiar_monto(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().lower()

    # falsos nulos
    if x in ["", "-", "none", "nan", "null"]:
        return np.nan

    # eliminar símbolos (moneda, letras)
    x = re.sub(r"[^\d,.\-]", "", x)

    if "," in x and "." in x:
        # europeo → coma decimal
        if x.rfind(",") > x.rfind("."):
            x = x.replace(".", "").replace(",", ".")
        else:
            x = x.replace(",", "")

    elif x.count(",") > 1:
        # miles con comas
        x = x.replace(",", "")

    elif "," in x:
        # decimal con coma
        x = x.replace(",", ".")

    return x

col = pedidos["monto"].apply(limpiar_monto)
pedidos["monto"] = pd.to_numeric(col, errors="coerce")

#estado
pedidos["estado"] = (
    pedidos["estado"].astype(str).str.strip().str.lower().map({
        "cancelado":"Cancelado",
        "preparacion":"Preparacion",
        "enviado":"Enviado",
        "pendiente":"Pendiente",
        "entregado":"Entregado"
        })
)

pedidos

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

pedidos_validos=pedidos[
    pedidos['id_cliente'].notna()&
    pedidos['fecha_pedido'].notna()&
    pedidos['monto'].notna()&
    pedidos['estado'].notna()
].copy()


pedidos_rechazados=pedidos[
    pedidos['id_cliente'].isna()|
    pedidos['fecha_pedido'].isna()|
    pedidos['monto'].isna()|
    pedidos['estado'].isna()
].copy()

#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['id_cliente']):
    motivos.append("id_cliente_vacio")

  if pd.isna(row['fecha_pedido']):
    motivos.append("fecha_pedido_vacio")

  if pd.isna(row['monto']):
    motivos.append("monto_vacio")

  if pd.isna(row['estado']):
    motivos.append("estado_vacio")

  return ";".join(motivos)

pedidos_rechazados["motivo_rechazo"] = pedidos_rechazados.apply(motivo,axis=1)

#VERIFICAR SI HAY DATOS NULOS
print(pedidos.isna().sum())

#EXPORTAR ARCHIVOS

pedidos_validos.to_csv("pedidos_curated.csv", index=False)

pedidos_rechazados.to_csv("pedidos_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

if pedidos_validos.empty:
    print("⚠ No hay datos válidos")

if pedidos_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    pedidos_validos.to_sql('pedidos_curated_parcial02', engine, if_exists='append', index=False)
    pedidos_rechazados.to_sql('pedidos_rejects_parcial02', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM pedidos_curated_parcial02 LIMIT 10",
    engine
)

#VALIDAR LA CARGA
pd.read_sql(
    "SELECT * FROM pedidos_rejects_parcial02 LIMIT 10",
    engine
)